services:
  petclinic-base:
    profiles: [do-not-use]
    image: "registry.atakama-technologies.com/vabf_petclinic:${VABF_VERSION:-1.2}-${PETCLINIC_VERSION:-3.3.0}-jre${JAVA_VERSION:-17}"
    build:  
      context: .
      dockerfile: Dockerfile
      target: ${VABF_TARGET:-build-and-run}
      args:
        - BUILD_IMAGE=8.9.0-jdk17-jammy
        - RUN_TOMCAT_IMAGE=10.1.24-jre17-temurin-jammy
        - AGENT_FOLDER=/usr/bin/nudge
    environment:
      - DB_PROFILE=${DB_PROFILE:-h2}
    ports:
      - "8082:8080"
    volumes:
      - "./agent/:/usr/bin/nudge"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
    networks:
      - vabf-net



  petclinic:
    profiles: ['']
    container_name: "ph_vabf"
    extends:
      service: petclinic-base

  petclinic-java8:
    profiles: [java8]
    container_name: "ph_vabf_java8"
    extends:
      service: petclinic
    build:
      args:
        - BUILD_IMAGE=8.9.0-jdk8-jammy
        - RUN_TOMCAT_IMAGE=9.0.89-jre8-temurin-jammy


  petclinic-mysql:
    profiles: [mysql]
    container_name: "ph_vabf_mysql"
    extends:
      service: petclinic-base
    depends_on:
      - mysql
    environment:
      - MYSQL_URL=jdbc:mysql://mysql/petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASS=petclinic

  mysql:
    profiles: [mysql]
    image: "mysql:8.4.0-oraclelinux9"
    container_name: "vabf-mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - vabf-net

  postgres:
    profiles: [postgres]
    image: postgres:16.3
    container_name: "vabf-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    networks:
      - vabf-net

networks:
  vabf-net:
    ipam:
      config:
        - subnet: "172.42.0.0/16"
