services:
  petclinic:
    container_name: ph_vabf
    image: "registry.atakama-technologies.com/vabf_petclinic:jdk21-1.1"
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - "./agent/:/spring-petclinic/nudge-agent"
    networks:
      - vabf-nudge
      
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql
  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres

networks:
  vabf-nudge:
    ipam:
      config:
        - subnet: "172.42.0.0/16"
